Remove thor-rails gem (#82)
Throws the following error when trying to launch the server:

```bash
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:129:in
`block in perform': undefined method `application' for
Thor::Rails:Module (NoMethodError)
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:125:in
`tap'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:125:in
`perform'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in
`run'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in
`invoke_command'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in
`dispatch'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0/lib/rails/command/base.rb:63:in
`perform'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0/lib/rails/command.rb:44:in
`invoke'
	from
/Users/kossyuzokwe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0/lib/rails/commands.rb:16:in
`<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

And frankly, don't see a reason why we had it in the first place.

Also removes the db thor task, as we'll be introducing seed data soon.